stages:
  - test
  - deploy

unittest:
  stage: test
  image: python:3.8
  script:
    - pip3 install numpy scipy
    - pip3 install pytest
    - pytest

################################################################################
# Deploy

.pypi:base: &pypi_template
  stage: deploy
  only:
    - master
  when: manual
  image: python:3.8
  script:
    - deploy.sh

pypi_test:
  <<: *pypi_template
  environment:
    name: PyPI Test
  variables:
    TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

pypi:
  <<: *pypi_template
  environment:
    name: PyPI
